---
- name: Remove all non-default configlets from all devices
  hosts: CVP
  connection: local
  vars: 
    path: "{{lookup('env','PWD')}}"
  vars_files: 
    - ../vars/CVP_model.yml
  tasks:
    - name: Apply configlets
      arista.cvp.cv_device_v3:
        devices: "{{ cvp_devices_base }}"
#        state: present
        apply_mode: strict