---
- name: Upload leaf1-Interface Configlets
  hosts: CVP
  connection: local
  vars: 
    path: "{{lookup('env','PWD')}}"
  vars_files: 
     - ../vars/CVP_model.yml
  tasks:
    - name: Upload Configlets for leaf1
      arista.cvp.cv_configlet_v3:
        configlets: "{{ cvp_configlets }}"
        state: present